import { Knex } from 'knex';

const ONG_ID = '11111111-1111-1111-1111-111111111111';

export async function seed(knex: Knex): Promise<void> {
  const existingOng = await knex('ongs').first();
  if (!existingOng) {
    await knex('ongs').insert({
      id: ONG_ID,
      name: 'ONG Patinhas Felizes',
      cnpj: '12.345.678/0001-90',
      phone: '(44) 99999-0001',
      address: 'Rua das Flores, 123 - Maringá/PR',
      city: 'Maringá',
      state: 'PR',
      status: 'approved',
    });
  } else {
    await knex('ongs')
      .where({ id: existingOng.id })
      .update({ city: 'Maringá', state: 'PR' });
  }

  const ongId = existingOng?.id || ONG_ID;

  const existingAnimals = await knex('animals').first();
  if (existingAnimals) {
    return;
  }

  const animals = [
    {
      id: 'aaaa0001-0001-0001-0001-000000000001',
      ong_id: ongId,
      name: 'Brisa',
      species: 'dog',
      breed: 'Labrador Retriever',
      sex: 'female',
      size: 'large',
      estimated_age_months: 24,
      temperament: 'Dócil',
      special_needs: false,
      description: 'Cachorra dócil e brincalhona, adora crianças.',
      photo_url: null,
      status: 'available',
    },
    {
      id: 'aaaa0001-0001-0001-0001-000000000002',
      ong_id: ongId,
      name: 'Thor',
      species: 'dog',
      breed: 'Pastor Alemão',
      sex: 'male',
      size: 'large',
      estimated_age_months: 36,
      temperament: 'Protetor',
      special_needs: false,
      description: 'Cão leal e protetor, ideal para casas com quintal.',
      photo_url: null,
      status: 'available',
    },
    {
      id: 'aaaa0001-0001-0001-0001-000000000003',
      ong_id: ongId,
      name: 'Luna',
      species: 'cat',
      breed: 'Siamês',
      sex: 'female',
      size: 'small',
      estimated_age_months: 12,
      temperament: 'Independente',
      special_needs: false,
      description: 'Gatinha independente e carinhosa.',
      photo_url: null,
      status: 'available',
    },
    {
      id: 'aaaa0001-0001-0001-0001-000000000004',
      ong_id: ongId,
      name: 'Rex',
      species: 'dog',
      breed: 'Vira-lata (SRD)',
      sex: 'male',
      size: 'medium',
      estimated_age_months: 18,
      temperament: 'Brincalhão',
      special_needs: false,
      description: 'Cachorro brincalhão e cheio de energia.',
      photo_url: null,
      status: 'available',
    },
    {
      id: 'aaaa0001-0001-0001-0001-000000000005',
      ong_id: ongId,
      name: 'Mimi',
      species: 'cat',
      breed: 'Persa',
      sex: 'female',
      size: 'small',
      estimated_age_months: 6,
      temperament: 'Calma',
      special_needs: false,
      description: 'Gatinha calma e ideal para apartamentos.',
      photo_url: null,
      status: 'available',
    },
    {
      id: 'aaaa0001-0001-0001-0001-000000000006',
      ong_id: ongId,
      name: 'Bob',
      species: 'dog',
      breed: 'Beagle',
      sex: 'male',
      size: 'medium',
      estimated_age_months: 8,
      temperament: 'Curioso',
      special_needs: false,
      description: 'Filhote curioso que adora explorar.',
      photo_url: null,
      status: 'available',
    },
    {
      id: 'aaaa0001-0001-0001-0001-000000000007',
      ong_id: ongId,
      name: 'Mel',
      species: 'dog',
      breed: 'Golden Retriever',
      sex: 'female',
      size: 'large',
      estimated_age_months: 48,
      temperament: 'Dócil',
      special_needs: true,
      special_needs_description: 'Possui displasia coxofemoral leve.',
      description: 'Cadela dócil com necessidade de cuidados especiais.',
      photo_url: null,
      status: 'available',
    },
    {
      id: 'aaaa0001-0001-0001-0001-000000000008',
      ong_id: ongId,
      name: 'Simba',
      species: 'cat',
      breed: 'Maine Coon',
      sex: 'male',
      size: 'medium',
      estimated_age_months: 30,
      temperament: 'Sociável',
      special_needs: false,
      description: 'Gato sociável que se dá bem com outros animais.',
      photo_url: null,
      status: 'available',
    },
    {
      id: 'aaaa0001-0001-0001-0001-000000000009',
      ong_id: ongId,
      name: 'Pipoca',
      species: 'dog',
      breed: 'Poodle',
      sex: 'female',
      size: 'small',
      estimated_age_months: 60,
      temperament: 'Alegre',
      special_needs: true,
      special_needs_description: 'Cega do olho esquerdo.',
      description: 'Cachorrinha alegre apesar da deficiência visual.',
      photo_url: null,
      status: 'available',
    },
    {
      id: 'aaaa0001-0001-0001-0001-000000000010',
      ong_id: ongId,
      name: 'Felix',
      species: 'cat',
      breed: 'Vira-lata (SRD)',
      sex: 'male',
      size: 'small',
      estimated_age_months: 4,
      temperament: 'Brincalhão',
      special_needs: false,
      description: 'Filhote brincalhão e cheio de energia.',
      photo_url: null,
      status: 'available',
    },
    {
      id: 'aaaa0001-0001-0001-0001-000000000011',
      ong_id: ongId,
      name: 'Max',
      species: 'dog',
      breed: 'Rottweiler',
      sex: 'male',
      size: 'large',
      estimated_age_months: 42,
      temperament: 'Protetor',
      special_needs: false,
      description: 'Cão protetor em processo de adoção.',
      photo_url: null,
      status: 'in_adoption_process',
    },
    {
      id: 'aaaa0001-0001-0001-0001-000000000012',
      ong_id: ongId,
      name: 'Nina',
      species: 'cat',
      breed: 'Angorá',
      sex: 'female',
      size: 'small',
      estimated_age_months: 15,
      temperament: 'Carinhosa',
      special_needs: false,
      description: 'Gata já adotada.',
      photo_url: null,
      status: 'adopted',
    },
  ];

  await knex('animals').insert(animals);
}
