sonar.projectKey=catdogmario
sonar.projectName=catdogmario
sonar.sources=services/backend/src,services/frontend/src
sonar.exclusions=**/node_modules/**,**/dist/**,**/*.spec.ts,**/__tests__/**,**/*.test.ts,**/*.test.tsx
sonar.typescript.tsconfigPaths=services/backend/tsconfig.json,services/frontend/tsconfig.json
sonar.javascript.lcov.reportPaths=services/backend/coverage/lcov.info,services/frontend/coverage/lcov.info